baseURL: "https://azkaastro.github.io/"
title: Abdurro'uf
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Mini CV
          url: /mini_cv/
          weight: 1
        - name: Publications
          url: /publications/
          weight: 2

params:
    description: "I'm an astrophysicist captivated by the cosmic journey of galaxies and how they evolve over billions of years. My research focuses on dissecting the intricate structures and star formation histories within galaxies to understand how they form, grow, and, in some cases, abruptly halt their star formation. A large part of my work revolves around piXedfit, a software tool I developed to perform spatially resolved spectral energy distribution (SED) fitting. By using data from powerful telescopes like JWST, HST, and Euclid, piXedfit enables me to create detailed maps of stellar populations in galaxies, from those nearby to those seen as they were just a billion years after the Big Bang."
    author: Abdurro'uf
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Abdurro'uf
          subtitle: "I'm an astrophysicist captivated by the cosmic journey of galaxies and how they evolve over billions of years. My research focuses on dissecting the intricate structures and star formation histories within galaxies to understand how they form, grow, and, eventually cease their star formation. My research centers on mapping these processes across cosmic time using **[piXedfit](https://github.com/aabdurrouf/piXedfit)**, a tool I developed for spatially resolved spectral energy distribution (SED) fitting. Leveraging data from telescopes like **JWST**, **HST**, and **Euclid**, I explore galaxies in stunning detail, from nearby to those seen as they were in the early universe."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Abdurro'uf
          buttons:
            - name: CV
              url: /mini_cv/
            - name: Publications
              url: /publications/
    socialIcons:
        - name: CV
          url: CV_oct_2024.pdf 
        - name: Email
          url: mailto:fabdurr1@jhu.edu
        - name: Location
          url: /location/
        - name: Google Scholar
          url: https://ui.adsabs.harvard.edu/search/p_=0&q=author%3A%22Abdurro'uf%22&sort=date%20desc%2C%20bibcode%20desc
        - name: orcid
          url: https://orcid.org/0000-0002-5258-8761
        - name: Arxiv
          url: https://arxiv.org/search/astro-ph?searchtype=author&query=Abdurro%27uf
        - name: GitHub
          url: https://github.com/aabdurrouf
        - name: linkedin
          url: https://www.linkedin.com/in/abdurro-uf-abdurro-uf-097860157/
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Abdurro'uf"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
